extensions: {}
cabal-file: project.cabal
extra-packages: ''
version: 1
environment: ghc-7.4.2-stable-13.09
module-template: ! 'module MODULE_NAME where

'
ghc-args: []
modules:
  Main(src/Main.hs):
    filename: src/Main.hs
  Data.Event:
    filename: src/Data/Event.hs
  Data.Stream.Persistence:
    filename: src/Data/Stream/Persistence.hs
  Data.Stream:
    filename: src/Data/Stream.hs
